# Copyright 2023 Intrinsic Innovation LLC

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(
    default_visibility = ["//visibility:public"],
)

bzl_library(
    name = "descriptor_set",
    srcs = ["descriptor_set.bzl"],
)
