# Copyright 2023 Intrinsic Innovation LLC

load("//bazel:go_macros.bzl", "go_library")

go_library(
    name = "intrinsic",
    srcs = ["init.go"],
    visibility = ["//intrinsic:public_api_users"],
)
