# Copyright 2023 Intrinsic Innovation LLC
# Intrinsic Proprietary and Confidential
# Provided subject to written agreement between the parties.

# proto-file: intrinsic/util/proto/get_text_proto_test.proto
# proto-message: intrinsic_proto.TestMessage
string_value: 3
unknown_field: "oops"
