# Copyright 2023 Intrinsic Innovation LLC

# Testing utilities for assets.

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "id_test_utils",
    srcs = ["id_test_utils.cc"],
    hdrs = ["id_test_utils.h"],
    deps = ["@com_google_absl//absl/strings"],
)
