# Copyright 2023 Intrinsic Innovation LLC
# Intrinsic Proprietary and Confidential
# Provided subject to written agreement between the parties.

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "realtime_annotations",
    hdrs = ["realtime_annotations.h"],
)
