# Copyright 2023 Intrinsic Innovation LLC

# Templates used by the external inctl tool.
package(default_visibility = ["//intrinsic/tools/inctl/cmd/bazel:__subpackages__"])

exports_files(
    srcs = [
        "BUILD",
        "empty_notebook.ipynb.template",
    ],
    visibility = [
        "//intrinsic/tools/inctl/cmd/notebook:__subpackages__",
    ],
)
