# Copyright 2023 Intrinsic Innovation LLC

# The update manager allows to manage updates

load("//bazel:go_macros.bzl", "go_library")

package(default_visibility = [
    "//intrinsic/frontend:__subpackages__",
    "//intrinsic/tools/inctl:__subpackages__",
])

go_library(
    name = "info",
    srcs = ["info.go"],
)
