# Copyright 2023 Intrinsic Innovation LLC

load("//bazel:go_macros.bzl", "go_library")

# Artifacts service client for inctl
package(default_visibility = ["//intrinsic/storage/artifacts:__subpackages__"])

go_library(
    name = "utils",
    srcs = ["utils.go"],
)
