# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/skills/proto/skill_manifest.proto
# proto-message: intrinsic_proto.skills.SkillManifest

id {
  package: "ai.intrinsic"
  name: "no_op"
}
display_name: "No op"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Does nothing, returns an OK status."
}
options {
  supports_cancellation: false
  python_config {
    skill_module: "intrinsic.skills.testing.no_op_skill"
    proto_module: "intrinsic.skills.testing.no_op_skill_pb2"
    create_skill: "intrinsic.skills.testing.no_op_skill.NoOpSkill"
  }
}
parameter {
  message_full_name: "intrinsic_proto.skills.NoOpSkillParams"
  default_value {
    [type.googleapis.com/intrinsic_proto.skills.NoOpSkillParams] {
      foo: "bar"
    }
  }
}
