# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/skills/proto/skill_manifest.proto
# proto-message: intrinsic_proto.skills.SkillManifest

id {
  package: "ai.intrinsic"
  name: "no_op"
}
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Does nothing, returns an OK status."
}
options {
  supports_cancellation: false
  cc_config {
    create_skill: "::intrinsic::skills::NoOpSkill::CreateSkill"
  }
}
parameter {
  message_full_name: "intrinsic_proto.skills.NoOpSkillParams"
}
