# Copyright 2023 Intrinsic Innovation LLC

# This package contains the shared middleware libraries built outside g3 in insrc.

exports_files(
    srcs = [
        "BUILD",
        "libimw_intraprocess_only_asan.so.1",
        "libimw_intraprocess_only_msan.so.1",
        "libimw_intraprocess_only_tsan.so.1",
        "libimw_zenoh.so.1",
    ],
    visibility = [
        "//intrinsic:__subpackages__",
    ],
)
