# Copyright 2023 Intrinsic Innovation LLC

""" Intrinsic package grasping.

This includes grasping related protos, grasp planning service and grasp skills."""

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "grasp_annotations_proto",
    srcs = ["grasp_annotations.proto"],
    deps = [
        "//intrinsic/math/proto:pose_proto",
        "//intrinsic/math/proto:vector3_proto",
    ],
)
